services:

  front-end:
    image: wesleymime/adopet-front-end
    restart: always
    ports:
      - "80:4200"

  api:
    image: wesleymime/adopet
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: adopet
      POSTGRES_PASSWORD: password_adopet
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 55067868+wesleymime@users.noreply.github.com
      PGADMIN_DEFAULT_PASSWORD: password_adopet
    ports:
      - "5050:80"
