version: '3.1'

services:

  web:
    build: ./src/main/js/angularclient/.
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: adopet
    ports:
      - "5432:5432"