services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: adopet
      POSTGRES_PASSWORD: password_adopet
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 55067868+wesleymime@users.noreply.github.com
      PGADMIN_DEFAULT_PASSWORD: password_adopet
    ports:
      - 5050:80
