spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true